services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app/tasks:/backend/app/tasks
    environment:
      - REDIS_URL=redis://redis:6379
